const { hashSync } = require('bcryptjs');

module.exports = async () => {
  return [
    {
      email: 'jim@email.com',
      password: hashSync('supersecretpassword'),
      first_name: 'Jim',
      last_name: 'Halpert',
      role: 'user',
      birthday: '2000-03-23',
      job: 'developer',
      active: false,
      icon: 'fa-regular fa-circle-5',
      hoursPerDay: 8,
    },
    {
      email: 'pam@email.com',
      password: hashSync('supersecretpassword'),
      first_name: 'Pam',
      last_name: 'Beesly',
      role: 'user',
      birthday: '2000-08-30',
      job: 'developer',
      active: true,
      icon: 'fa-solid fa-circle',
      hoursPerDay: 4,
    },
    {
      email: 'serban@chesscoders.com',
      password: hashSync('supersecretpassword'),
      first_name: 'Serban',
      last_name: 'Capatina',
      role: 'user',
      birthday: '2000-08-30',
      job: 'Intern Web Developer',
      active: true,
      hoursPerDay: 8,
    },
    {
      email: 'artur@email.com',
      password: hashSync('supersecretpassword'),
      first_name: 'Arthur',
      last_name: 'Spunei',
      role: 'user',
      birthday: '2000-03-14',
      job: 'intern developer',
      active: true,
      icon: 'fa-regular fa-circle-5',
      hoursPerDay: 4,
    },
    {
      email: 'leonard@chesscoders.com',
      password: hashSync('supersecretpassword'),
      first_name: 'Leonard',
      last_name: 'Ionescu',
      role: 'user',
      birthday: '2000-08-30',
      job: 'Intern Web Developer',
      active: true,
      hoursPerDay: 8,
    },
    {
      email: 'alexandra@chesscoders.com',
      password: hashSync('supersecretpassword'),
      first_name: 'Alexandra',
      last_name: 'Sfetcu',
      role: 'user',
      birthday: '1999-08-30',
      job: 'Intern Web Developer',
      active: true,
      hoursPerDay: 4,
    },
  ];
};
