const create = require('./create');
const readMany = require('./read-many');
const readOne = require('./read-one');
const remove = require('./remove');
const update = require('./update');
const votePoll = require('./vote-poll');
const approvePoll = require('./approve-poll');
const rejectPoll = require('./reject-poll');
const activatePoll = require('./activate-poll');
const deactivatePoll = require('./deactivate-poll');

module.exports = {
  create,
  readMany,
  readOne,
  remove,
  update,
  votePoll,
  approvePoll,
  rejectPoll,
  activatePoll,
  deactivatePoll,
};
/* auto-generated by robocode v0.4.3 */
