const { error } = require('../../functions');
const { Poll } = require('../../models');

module.exports = async (req, res) => {
  const { id } = req.params;
  if (!id) {
    throw error(400, 'Missing required params');
  }

  const document = await Poll.findById(id).lean();
  if (!document) {
    throw error(404, 'Poll was not found');
  }

  await Poll.findByIdAndDelete(id);

  return res.status(200).send({
    message: 'Poll was deleted successfully',
  });
};
/* auto-generated by robocode v0.4.3 */
